name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      #checks out repository
      - uses: actions/checkout@v2
        with:
          project: '.'
      
      #install node version 12
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      #install npm packages
      - name: install packages
        run: npm install
      
      #Build react app
      - name: Build application
        run: npm run build
      
      #install surge
      - name: Install surge
        run: npm install -g surge
      
      - name: deploy to surge
        run: surge ./build zephyr-it.surge.sh --token ${{secrets.TOKEN}}
        
