name: Deploy to Surge

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      #checks out repository
      - uses: actions/checkout@v2
      
      #install node version 12
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      #install npm packages
      - name: install packages
        working-directory: ./frontend
        run: npm install
      
      #Build react app
      - name: Build application
        working-directory: ./frontend
        run: npm run build
      
      #install surge
      - name: Install surge
        run: npm install -g surge
      
      - name: deploy to surge
        working-directory: ./frontend
        run: surge ./build zephyr-it.surge.sh --token ${{secrets.TOKEN}}
        
